/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.valdir.view;

import br.valdir.modelBeans.BeansUsuario;
import br.valdir.modelBeans.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelConection.ConexaoBD;
import modelDao.DaoUsuario;

/**
 *
 * @author Valdir
 */
public class FormUsuario extends javax.swing.JFrame {

    BeansUsuario mod = new BeansUsuario();
    DaoUsuario dao = new DaoUsuario();
    ConexaoBD conex = new ConexaoBD();

    int flag = 1;

    public FormUsuario() {
        initComponents();
        preencherTabela("select * from usuarios order by uso_nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jtConfSenha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jcTipo = new javax.swing.JComboBox<>();
        jtPesquisar = new javax.swing.JTextField();
        jLabelPesquisar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtCod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Usuários");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 0, 260, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nome:");

        jtNome.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Usuário:");

        jtUsuario.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Senha:");

        jtSenha.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Confirmar Senha:");

        jtConfSenha.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tipo:");

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "médico", "recepcionista" }));
        jcTipo.setEnabled(false);

        jLabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/procurar.png"))); // NOI18N
        jLabelPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPesquisarMouseClicked(evt);
            }
        });

        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        jbtNovo.setText("Novo");
        jbtNovo.setMaximumSize(new java.awt.Dimension(119, 119));
        jbtNovo.setMinimumSize(null);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setText("Salvar");
        jbtSalvar.setEnabled(false);
        jbtSalvar.setMaximumSize(new java.awt.Dimension(119, 119));
        jbtSalvar.setMinimumSize(null);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.setEnabled(false);
        jbtCancelar.setMaximumSize(new java.awt.Dimension(119, 119));
        jbtCancelar.setMinimumSize(null);
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtEditar.setText("Editar");
        jbtEditar.setEnabled(false);
        jbtEditar.setMaximumSize(new java.awt.Dimension(119, 119));
        jbtEditar.setMinimumSize(null);
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.setEnabled(false);
        jbtExcluir.setMaximumSize(new java.awt.Dimension(119, 119));
        jbtExcluir.setMinimumSize(null);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Cod Usuário:");

        jtCod.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(jtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelPesquisar)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPesquisar)
                    .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 650, 350);

        setSize(new java.awt.Dimension(686, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        flag = 1;
        jtPesquisar.setEnabled(false);
        jLabelPesquisar.setVisible(false);
        jtCod.setText("");
        jtNome.setEnabled(true);
        jtSenha.setEnabled(true);
        jtUsuario.setEnabled(true);
        jtConfSenha.setEnabled(true);
        jbtSalvar.setEnabled(true);
        jcTipo.setEnabled(true);
        jbtCancelar.setEnabled(true);
        jbtNovo.setEnabled(false);
        jbtEditar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        jtNome.requestFocus();
        jtNome.setText("");
        jtUsuario.setText("");
        jtSenha.setText("");
        jtConfSenha.setText("");
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        String senha = new String(jtSenha.getPassword());
        if (jtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NOME nao pode estar vazio");
            jtNome.requestFocus();
        } else if (jtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo USUÁRIO nao pode estar vazio");
            jtUsuario.requestFocus();
        } else if (jtSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo SENHA nao pode estar vazio");
        } else if (jtConfSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CONFIRMA SENHA nao pode estar vazio");
        } else if(!jtSenha.getText().equals(jtConfSenha.getText())){
            JOptionPane.showMessageDialog(null, "As senhas naop conferem");
            jtSenha.setText("");
            jtConfSenha.setText("");
            jtSenha.requestFocus();
        }else
            
            if (flag == 1) {
            mod.setUsoNome(jtNome.getText());
            mod.setUsoUsuario(jtUsuario.getText());
            mod.setUsoSenha(senha);
            mod.setUsoTipo((String) jcTipo.getSelectedItem());
            dao.salvar(mod);
            jtNome.setText("");
            jtNome.setEnabled(false);
            jtUsuario.setText("");
            jtUsuario.setEnabled(false);
            jtSenha.setText("");
            jtSenha.setEnabled(false);
            jtConfSenha.setText("");
            jtConfSenha.setEnabled(false);
            jbtCancelar.setEnabled(false);
            jbtSalvar.setEnabled(false);
            jbtNovo.setEnabled(true);
            jtPesquisar.setEnabled(true);
            jLabelPesquisar.setVisible(true);
            preencherTabela("select * from usuarios order by uso_nome");
        }else{
            mod.setUsoCod((Integer.parseInt(jtCod.getText())));
            mod.setUsoNome(jtNome.getText());
            mod.setUsoUsuario(jtUsuario.getText());
            mod.setUsoSenha(senha);
            mod.setUsoTipo((String) jcTipo.getSelectedItem());
            dao.Editar(mod);
            jtNome.setText("");
            jtNome.setEnabled(false);
            jtUsuario.setText("");
            jtUsuario.setEnabled(false);
            jtSenha.setText("");
            jtSenha.setEnabled(false);
            jtConfSenha.setText("");
            jtConfSenha.setEnabled(false);
            jbtCancelar.setEnabled(false);
            jbtSalvar.setEnabled(false);
            jbtNovo.setEnabled(true);            
            jtPesquisar.setEnabled(true);
            jLabelPesquisar.setVisible(true);
            preencherTabela("select * from usuarios order by uso_nome");  
            }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
       flag = 2;
       jtNome.setEnabled(true);
       jtSenha.setEnabled(true);
       jtUsuario.setEnabled(true);
       jtConfSenha.setEnabled(true);
       jbtSalvar.setEnabled(true);
       jcTipo.setEnabled(true);
       jbtSalvar.setEnabled(true);
       jbtCancelar.setEnabled(true);
       jbtEditar.setEnabled(false);
       jbtNovo.setEnabled(false);
       jbtExcluir.setEnabled(false);
       jtPesquisar.setEnabled(false);
       jLabelPesquisar.setVisible(false);
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jLabelPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPesquisarMouseClicked
        mod.setPesquisa(jtPesquisar.getText());
        BeansUsuario model = dao.buscaUsuario(mod);
        jtCod.setText(String.valueOf(model.getUsoCod()));
        jtNome.setText(model.getUsoNome());
        jtUsuario.setText(model.getUsoUsuario());
        jtSenha.setText(model.getUsoSenha());
        jtSenha.setText(model.getUsoSenha());
        jtConfSenha.setText(model.getUsoSenha());
        jcTipo.setSelectedItem(model.getUsoTipo());
        
        preencherTabela("select *from usuarios where uso_nome ~*'" + mod.getPesquisa() + "'");
    }//GEN-LAST:event_jLabelPesquisarMouseClicked

    private void jtTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaMouseClicked
        String nome_usuario = ""+jtTabela.getValueAt(jtTabela.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("SELECT * FROM usuarios where uso_nome='"+nome_usuario+"'");
        try {
            conex.rs.first();
            jtCod.setText(String.valueOf(conex.rs.getInt("cod_usuario")));
            jtPesquisar.setText(conex.rs.getString("uso_nome"));
            jtNome.setText(conex.rs.getString("uso_nome"));
            jtUsuario.setText(conex.rs.getString("uso_usuario"));
            jtSenha.setText(conex.rs.getString("uso_senha"));
            jtConfSenha.setText(conex.rs.getString("uso_senha"));
            jcTipo.setSelectedItem(conex.rs.getString("uso_tipo"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados"+ex);
        }
        conex.desconecta();
        jbtEditar.setEnabled(true);
        jbtExcluir.setEnabled(true);
        jbtNovo.setEnabled(true);
        jbtSalvar.setEnabled(false);
        jtPesquisar.setEnabled(true);
        jLabelPesquisar.setVisible(true);
        
    }//GEN-LAST:event_jtTabelaMouseClicked

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        flag=1;
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir ?");
        if (resposta == JOptionPane.YES_OPTION) { 
        mod.setUsoCod((Integer.parseInt(jtCod.getText())));
        dao.Excluir(mod);
        jtCod.setText("");
        jtNome.setText("");
        jtNome.setEnabled(false);
        jtUsuario.setText("");
        jtUsuario.setEnabled(false);
        jtSenha.setText("");
        jtSenha.setEnabled(false);
        jtConfSenha.setText("");
        jtConfSenha.setEnabled(false);
        jbtCancelar.setEnabled(false);
        jbtSalvar.setEnabled(false);
        jbtEditar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        jbtNovo.setEnabled(true);
        jtPesquisar.setEnabled(true);
        jLabelPesquisar.setVisible(true);
        preencherTabela("select * from usuarios order by uso_nome");
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        jtNome.setText("");
        jtNome.setEnabled(false);
        jtUsuario.setText("");
        jtUsuario.setEnabled(false);
        jtSenha.setText("");
        jtSenha.setEnabled(false);
        jtConfSenha.setText("");
        jtConfSenha.setEnabled(false);
        jbtCancelar.setEnabled(false);
        jbtSalvar.setEnabled(false);
        jbtEditar.setEnabled(false);
        jbtExcluir.setEnabled(false);
        jbtNovo.setEnabled(true);  
        jtPesquisar.setEnabled(true);
        jLabelPesquisar.setVisible(true);
    }//GEN-LAST:event_jbtCancelarActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String []colunas = new String[]{"Cod_Usuário","Nome","Usuário","Tipo"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
               dados.add(new Object[]{conex.rs.getInt("cod_usuario"),conex.rs.getString("uso_nome"),conex.rs.getString("uso_usuario"),conex.rs.getString("uso_tipo")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            //JOptionPane.showMessageDialog(rootPane,"Usuario não cadastrado");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jtTabela.setModel(modelo);
        jtTabela.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtTabela.getColumnModel().getColumn(0).setResizable(false);
        jtTabela.getColumnModel().getColumn(1).setPreferredWidth(300);
        jtTabela.getColumnModel().getColumn(1).setResizable(false);
        jtTabela.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtTabela.getColumnModel().getColumn(2).setResizable(false);
        jtTabela.getColumnModel().getColumn(3).setPreferredWidth(105);
        jtTabela.getColumnModel().getColumn(3).setResizable(false);
        jtTabela.getTableHeader().setReorderingAllowed(false);
        jtTabela.setAutoResizeMode(jtTabela.AUTO_RESIZE_OFF);
        jtTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JTextField jtCod;
    private javax.swing.JPasswordField jtConfSenha;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JTable jtTabela;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
