/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.valdir.view;

import br.valdir.modelBeans.BeansPaciente;
import br.valdir.modelBeans.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelConection.ConexaoBD;
import modelDao.DaoPaciente;

/**
 *
 * @author Valdir
 */
public class FormPaciente extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    BeansPaciente mod = new BeansPaciente();
    DaoPaciente dao = new DaoPaciente();
    int flag = 0;

    public FormPaciente() {
        initComponents();
        preencherBairro();
        preencherTabela("select * from pacientes order by pac_nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jfRG = new javax.swing.JFormattedTextField();
        jfTelefone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jtNum = new javax.swing.JTextField();
        jtCep = new javax.swing.JFormattedTextField();
        jtComplemento = new javax.swing.JTextField();
        jtCidade = new javax.swing.JTextField();
        jtEstado = new javax.swing.JTextField();
        jcVila = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jfCel = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultado = new javax.swing.JTable();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtAlterar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jtPesquisar = new javax.swing.JTextField();
        jlPes = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jfNascimento = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome: ");

        jLabel3.setText("Nascimento: ");

        jLabel4.setText("Telefone: ");

        jLabel5.setText("RG: ");

        jtNome.setEnabled(false);

        try {
            jfRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfRG.setEnabled(false);

        try {
            jfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfTelefone.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel6.setText("Rua: ");

        jLabel7.setText("Cep: ");

        jLabel8.setText("Complemento: ");

        jLabel9.setText("Bairro: ");

        jLabel10.setText("Nº");

        jLabel11.setText("Cidade: ");

        jLabel12.setText("Estado: ");

        jtRua.setEnabled(false);

        jtNum.setEnabled(false);

        try {
            jtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCep.setEnabled(false);

        jtComplemento.setEnabled(false);

        jtCidade.setEnabled(false);

        jtEstado.setEnabled(false);
        jtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEstadoActionPerformed(evt);
            }
        });

        jcVila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcVila.setEnabled(false);
        jcVila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcVilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(306, 306, 306)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtComplemento)
                            .addComponent(jtEstado)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcVila, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcVila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Cel:");

        try {
            jfCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfCel.setEnabled(false);

        jTableResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableResultado);

        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setText("Salvar");
        jbtSalvar.setEnabled(false);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.setEnabled(false);
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtAlterar.setText("Alterar");
        jbtAlterar.setEnabled(false);
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.setEnabled(false);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jlPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/procurar.png"))); // NOI18N
        jlPes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlPesMouseClicked(evt);
            }
        });

        jLabel15.setText("Id :");

        jtId.setEnabled(false);

        try {
            jfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfNascimento.setEnabled(false);
        jfNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPes))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jfTelefone)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jfCel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jfNascimento))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jfCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPes)
                    .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNovo)
                    .addComponent(jbtSalvar)
                    .addComponent(jbtCancelar)
                    .addComponent(jbtAlterar)
                    .addComponent(jbtExcluir))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 598, 580);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Formulário de Pacientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 0, 288, 29);

        setSize(new java.awt.Dimension(625, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void preencherBairro() {
        conex.conexao();
        conex.executaSql("Select * from bairro order by bai_nome");
        try {
            conex.rs.first();
            jcVila.removeAllItems();
            do {
                jcVila.addItem(conex.rs.getString("bai_nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher bairros" + ex);
        }
        conex.desconecta();
    }

    private void jtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEstadoActionPerformed

    private void jcVilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcVilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcVilaActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        if (jtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo NOME nao pode estar vazio");
            jtNome.requestFocus();
        } else if (jfRG.getText().equals("  .   .   - ")) {
            JOptionPane.showMessageDialog(null, "O campo RG nao pode estar vazio");
            jfRG.requestFocus();
        } else if (jfCel.getText().equals("(  )     -    ")) {
            JOptionPane.showMessageDialog(null, "O campo CELULAR nao pode estar vazio");
            jfCel.requestFocus();
        } else if (jtRua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo RUA nao pode estar vazio");
            jtRua.requestFocus();
        } else if (jtCep.getText().equals("     -   ")) {
            JOptionPane.showMessageDialog(null, "O campo CEP nao pode estar vazio");
            jtCep.requestFocus();
        } else if (jtNum.getText().equals("(  )    -    ")) {
            JOptionPane.showMessageDialog(null, "O campo Nº nao pode estar vazio");
            jtNum.requestFocus();
        } else if (jtCidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo CIDADE nao pode estar vazio");
            jtCidade.requestFocus();
        } else if (jtEstado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo ESTADO nao pode estar vazio");
            jtEstado.requestFocus();
        } else if (jfNascimento.getText().equals("  /  /  ")) {
            JOptionPane.showMessageDialog(null, "O campo DATA DE NASCIMENTO nao pode estar vazio");
            jfNascimento.requestFocus();

        } else if (flag == 1) {
            mod.setPac_nome(jtNome.getText());
            mod.setPac_rg(jfRG.getText());
            mod.setPac_telefone(jfTelefone.getText());
            mod.setPac_celular(jfCel.getText());
            mod.setPac_rua(jtRua.getText());
            mod.setPac_cep(jtCep.getText());
            mod.setPac_numero(jtNum.getText());
            mod.setPac_complemento(jtComplemento.getText());
            mod.setPac_cidade(jtCidade.getText());
            mod.setPac_estado(jtEstado.getText());
            mod.setBairro((String) jcVila.getSelectedItem());
            mod.setPac_nasc(jfNascimento.getText());
            dao.Salvar(mod);
            jbtNovo.setEnabled(true);
            jcVila.setEnabled(false);
            jtCep.setText("");
            jtCep.setEnabled(false);
            jtCidade.setText("");
            jtCidade.setEnabled(false);
            jtComplemento.setText("");
            jtComplemento.setEnabled(false);
            jtEstado.setText("");
            jtEstado.setEnabled(false);
            jtId.setText("");
            jtNome.setText("");
            jtNome.setEnabled(false);
            jtNum.setText("");
            jtNum.setEnabled(false);
            jtPesquisar.setText("");
            jtPesquisar.setEnabled(true);
            jtPesquisar.setEditable(true);
            jtRua.setText("");
            jtRua.setEnabled(false);
            jfCel.setText("");
            jfCel.setEnabled(false);
            jfNascimento.setText("");
            jfNascimento.setEnabled(false);
            jfRG.setText("");
            jfRG.setEnabled(false);
            jfTelefone.setText("");
            jfTelefone.setEnabled(false);
            jbtSalvar.setEnabled(false);
            jbtCancelar.setEnabled(false);
            jlPes.setVisible(true);
            preencherTabela("select * from pacientes order by pac_nome");
        } else {
            if (jtNome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo NOME nao pode estar vazio");
                jtNome.requestFocus();
            } else if (jfRG.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo RG nao pode estar vazio");
                jfRG.requestFocus();
            } else if (jfCel.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo CELULAR nao pode estar vazio");
                jfCel.requestFocus();
            } else if (jtRua.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo RUA nao pode estar vazio");
                jtRua.requestFocus();
            } else if (jtCep.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo CEP nao pode estar vazio");
                jtCep.requestFocus();
            } else if (jtNum.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Nº nao pode estar vazio");
                jtNum.requestFocus();
            } else if (jtCidade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo CIDADE nao pode estar vazio");
                jtCidade.requestFocus();
            } else if (jtEstado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo ESTADO nao pode estar vazio");
                jtEstado.requestFocus();
            } else if (jfNascimento.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo DATA DE NASCIMENTO nao pode estar vazio");
                jfNascimento.requestFocus();

            } else {
                mod.setPac_nome(jtNome.getText());
            }
            mod.setPac_rg(jfRG.getText());
            mod.setPac_telefone(jfTelefone.getText());
            mod.setPac_celular(jfCel.getText());
            mod.setPac_rua(jtRua.getText());
            mod.setPac_cep(jtCep.getText());
            mod.setPac_numero(jtNum.getText());
            mod.setPac_complemento(jtComplemento.getText());
            mod.setPac_cidade(jtCidade.getText());
            mod.setPac_estado(jtEstado.getText());
            mod.setBairro((String) jcVila.getSelectedItem());
            mod.setPac_nasc(jfNascimento.getText());
            mod.setCod_paciente(Integer.parseInt(jtId.getText()));
            dao.Alterar(mod);
            jbtNovo.setEnabled(true);
            jcVila.setEnabled(false);
            jtCep.setText("");
            jtCep.setEnabled(false);
            jtCidade.setText("");
            jtCidade.setEnabled(false);
            jtComplemento.setText("");
            jtComplemento.setEnabled(false);
            jtEstado.setText("");
            jtEstado.setEnabled(false);
            jtId.setText("");
            jtNome.setText("");
            jtNome.setEnabled(false);
            jtNum.setText("");
            jtNum.setEnabled(false);
            jtPesquisar.setText("");
            jtPesquisar.setEnabled(true);
            jtPesquisar.setEditable(true);
            jtRua.setText("");
            jtRua.setEnabled(false);
            jfCel.setText("");
            jfCel.setEnabled(false);
            jfNascimento.setText("");
            jfNascimento.setEnabled(false);
            jfRG.setText("");
            jfRG.setEnabled(false);
            jfTelefone.setText("");
            jfTelefone.setEnabled(false);
            jbtSalvar.setEnabled(false);
            jbtCancelar.setEnabled(false);
            jlPes.setVisible(true);
            preencherTabela("select * from pacientes order by pac_nome");
        }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        flag = 1;
        jbtExcluir.setEnabled(false);
        jbtAlterar.setEnabled(false);
        jbtNovo.setEnabled(false);
        jcVila.setEnabled(true);
        jtCep.setText("");
        jtCep.setEnabled(true);
        jtCidade.setText("");
        jtCidade.setEnabled(true);
        jtComplemento.setText("");
        jtComplemento.setEnabled(true);
        jtEstado.setText("");
        jtEstado.setEnabled(true);
        jtId.setText("");
        jtNome.setText("");
        jtNome.setEnabled(true);
        jtNum.setText("");
        jtNum.setEnabled(true);
        jtPesquisar.setText("");
        jtPesquisar.setEnabled(false);
        jtPesquisar.setEditable(false);
        jtRua.setText("");
        jtRua.setEnabled(true);
        jfCel.setText("");
        jfCel.setEnabled(true);
        jfNascimento.setText("");
        jfNascimento.setEnabled(true);
        jfRG.setText("");
        jfRG.setEnabled(true);
        jfTelefone.setText("");
        jfTelefone.setEnabled(true);
        jbtSalvar.setEnabled(true);
        jbtCancelar.setEnabled(true);
        jlPes.setVisible(false);
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
        flag = 2;
        jbtNovo.setEnabled(false);
        jcVila.setEnabled(true);
        jtCep.setEnabled(true);
        jtCidade.setEnabled(true);
        jtComplemento.setEnabled(true);
        jtEstado.setEnabled(true);
        jtNome.setEnabled(true);
        jtNum.setEnabled(true);
        jtPesquisar.setText("");
        jtPesquisar.setEnabled(false);
        jtPesquisar.setEditable(false);
        jtRua.setEnabled(true);
        jfCel.setEnabled(true);
        jfNascimento.setEnabled(true);
        jfRG.setEnabled(true);
        jfTelefone.setEnabled(true);
        jbtSalvar.setEnabled(true);
        jbtCancelar.setEnabled(true);
        jlPes.setVisible(false);
        jbtAlterar.setEnabled(false);
        jbtExcluir.setEnabled(false);

    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jlPesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlPesMouseClicked

        mod.setPesquisar(jtPesquisar.getText());
        flag = 2;
        jbtExcluir.setEnabled(true);
        jbtAlterar.setEnabled(true);
        BeansPaciente mod2 = dao.buscarPas(mod);
        jtId.setText(String.valueOf(mod2.getCod_paciente()));
        jtNome.setText(mod2.getPac_nome());
        jfRG.setText(mod2.getPac_rg());
        jfTelefone.setText(mod2.getPac_telefone());
        jfCel.setText(mod2.getPac_celular());
        jfNascimento.setText(mod2.getPac_nasc());
        jtRua.setText(mod2.getPac_rua());
        jtCep.setText(mod2.getPac_cep());
        jtNum.setText(mod2.getPac_numero());
        jtComplemento.setText(mod2.getPac_complemento());
        jtCidade.setText(mod2.getPac_cidade());
        jtEstado.setText(mod2.getPac_estado());
        jcVila.addItem(mod2.getBairro());

    }//GEN-LAST:event_jlPesMouseClicked

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        flag = 1;
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir ?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCod_paciente(Integer.parseInt(jtId.getText()));
            dao.Excluir(mod);
            jtCep.setText("");
            jtCidade.setText("");
            jtComplemento.setText("");
            jtEstado.setText("");
            jtId.setText("");
            jtNome.setText("");
            jtNum.setText("");
            jtPesquisar.setText("");
            jtRua.setText("");
            jfCel.setText("");
            jfNascimento.setText("");
            jfRG.setText("");
            jfTelefone.setText("");
            preencherTabela("select * from pacientes order by pac_nome");
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        flag = 1;
        jbtNovo.setEnabled(true);
        jcVila.setEnabled(false);
        jtCep.setText("");
        jtCep.setEnabled(false);
        jtCidade.setText("");
        jtCidade.setEnabled(false);
        jtComplemento.setText("");
        jtComplemento.setEnabled(false);
        jtEstado.setText("");
        jtEstado.setEnabled(false);
        jtId.setText("");
        jtNome.setText("");
        jtNome.setEnabled(false);
        jtNum.setText("");
        jtNum.setEnabled(false);
        jtPesquisar.setText("");
        jtPesquisar.setEnabled(true);
        jtPesquisar.setEditable(true);
        jtRua.setText("");
        jtRua.setEnabled(false);
        jfCel.setText("");
        jfCel.setEnabled(false);
        jfNascimento.setText("");
        jfNascimento.setEnabled(false);
        jfRG.setText("");
        jfRG.setEnabled(false);
        jfTelefone.setText("");
        jfTelefone.setEnabled(false);
        jbtSalvar.setEnabled(false);
        jbtCancelar.setEnabled(false);
        jlPes.setVisible(true);
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jTableResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultadoMouseClicked
        String nome_paciente = "" + jTableResultado.getValueAt(jTableResultado.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("SELECT * FROM pacientes where pac_nome='" + nome_paciente + "'");
        try {
            conex.rs.first();
            jtId.setText(String.valueOf(conex.rs.getInt("cod_paciente")));
            jtNome.setText(conex.rs.getString("pac_nome"));
            jfRG.setText(conex.rs.getString("pac_rg"));
            jfTelefone.setText(conex.rs.getString("pac_telefone"));
            jfCel.setText(conex.rs.getString("pac_celular"));
            jfNascimento.setText(conex.rs.getString("pac_nasc"));
            jtRua.setText(conex.rs.getString("pac_rua"));
            jtCep.setText(conex.rs.getString("pac_cep"));
            jtNum.setText(conex.rs.getString("pac_numero"));
            jtComplemento.setText(conex.rs.getString("pac_complemento"));
            jtCidade.setText(conex.rs.getString("pac_cidade"));
            jtEstado.setText(conex.rs.getString("pac_estado"));
            ConexaoBD conexaoBai = new ConexaoBD();
            conexaoBai.conexao();
            conexaoBai.executaSql("select * from bairro where cod_bairro='" + conex.rs.getInt("pac_cod_bairro") + "'");
            conexaoBai.rs.first();
            jcVila.setSelectedItem(conexaoBai.rs.getString("bai_nome"));

            conexaoBai.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados" + ex);
        }
        conex.desconecta();
        jbtAlterar.setEnabled(true);
        jbtExcluir.setEnabled(true);
        jbtNovo.setEnabled(true);
        jbtCancelar.setEnabled(true);
    }//GEN-LAST:event_jTableResultadoMouseClicked

    private void jfNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfNascimentoActionPerformed

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome", "Data Nascimento", "Celular"};
        conex.conexao();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("cod_paciente"), conex.rs.getString("pac_nome"), conex.rs.getString("pac_nasc"), conex.rs.getString("pac_celular")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Paciente nao encontrado");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableResultado.setModel(modelo);
        jTableResultado.getColumnModel().getColumn(0).setPreferredWidth(65);
        jTableResultado.getColumnModel().getColumn(0).setResizable(false);
        jTableResultado.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableResultado.getColumnModel().getColumn(1).setResizable(false);
        jTableResultado.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTableResultado.getColumnModel().getColumn(2).setResizable(false);
        jTableResultado.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableResultado.getColumnModel().getColumn(3).setResizable(false);
        jTableResultado.getTableHeader().setReorderingAllowed(false);
        jTableResultado.setAutoResizeMode(jTableResultado.AUTO_RESIZE_OFF);
        jTableResultado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultado;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox<String> jcVila;
    private javax.swing.JFormattedTextField jfCel;
    private javax.swing.JFormattedTextField jfNascimento;
    private javax.swing.JFormattedTextField jfRG;
    private javax.swing.JFormattedTextField jfTelefone;
    private javax.swing.JLabel jlPes;
    private javax.swing.JFormattedTextField jtCep;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNum;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTextField jtRua;
    // End of variables declaration//GEN-END:variables
}
