/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.valdir.view;

import modelConection.ConexaoBD;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Valdir
 */
public class TelaPrincipal extends javax.swing.JFrame {

  
    ConexaoBD conecta = new ConexaoBD();
    FormMedico tela = new FormMedico();
    FormUsuario telaUsu = new FormUsuario();
    FormPaciente telaPas = new FormPaciente();
    FormAgenda telaAge = new FormAgenda();
    FormAgendados telaAgen = new FormAgendados();
    FormAgendaMedico telaAgenM = new FormAgendaMedico();

    public TelaPrincipal(String usuario) {
        initComponents();
        setIcon();
        jLabelUsuario.setText(usuario);
        conecta.conexao();
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameInternal = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonCadEnfermeiras = new javax.swing.JButton();
        jButtonCadPAciente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadMedico = new javax.swing.JMenuItem();
        jMenuItemCadPaciente = new javax.swing.JMenuItem();
        jMenuItemCadEnfermeira = new javax.swing.JMenuItem();
        jMenuItemCadUsuario = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelPaciente = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BEM-VINDO AO WS_MEDICAL");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameInternal.setTitle("Bem-Vindo");
        jInternalFrameInternal.setVisible(true);
        jInternalFrameInternal.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 91, 98));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/doctor.png"))); // NOI18N
        jButton1.setToolTipText("Cadastro de Medicos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButton1);
        jButton1.setBounds(20, 30, 130, 130);

        jButtonCadEnfermeiras.setBackground(new java.awt.Color(234, 73, 73));
        jButtonCadEnfermeiras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/nurse.png"))); // NOI18N
        jButtonCadEnfermeiras.setToolTipText("Cadastro de Enfermeiras");
        jPanelInternal.add(jButtonCadEnfermeiras);
        jButtonCadEnfermeiras.setBounds(160, 30, 130, 130);

        jButtonCadPAciente.setBackground(new java.awt.Color(50, 74, 94));
        jButtonCadPAciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/team.png"))); // NOI18N
        jButtonCadPAciente.setToolTipText("Cadastro de Pacientes");
        jButtonCadPAciente.setBorder(null);
        jButtonCadPAciente.setBorderPainted(false);
        jButtonCadPAciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPAcienteActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadPAciente);
        jButtonCadPAciente.setBounds(300, 30, 130, 130);

        jLabel3.setText("Agenda -");
        jPanelInternal.add(jLabel3);
        jLabel3.setBounds(20, 170, 60, 14);

        jButtonAgenda.setBackground(new java.awt.Color(255, 198, 40));
        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/calendar (1).png"))); // NOI18N
        jButtonAgenda.setToolTipText("Agenda");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonAgenda);
        jButtonAgenda.setBounds(20, 190, 130, 130);

        jLabel4.setText("Cadastros -");
        jPanelInternal.add(jLabel4);
        jLabel4.setBounds(20, 10, 70, 14);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/internalframe.png"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(-110, -50, 990, 460);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/fundo_telaprincipal.jpg"))); // NOI18N
        jPanelInternal.add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 810, 580);

        jInternalFrameInternal.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(-10, 70, 820, 370);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFrameInternal.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 390, 40);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/valdir/img/exit.png"))); // NOI18N
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jInternalFrameInternal.getContentPane().add(jButtonFechar);
        jButtonFechar.setBounds(750, 0, 40, 40);

        getContentPane().add(jInternalFrameInternal);
        jInternalFrameInternal.setBounds(10, 20, 810, 510);

        jLabel2.setText("Bem vindo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 550, 60, 14);

        jLabelUsuario.setText("jLabel5");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(80, 550, 210, 14);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadMedico.setText("Medicos");
        jMenuItemCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadMedico);

        jMenuItemCadPaciente.setText("Pacientes");
        jMenuItemCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadPaciente);

        jMenuItemCadEnfermeira.setText("Enfermeiras");
        jMenuCadastro.add(jMenuItemCadEnfermeira);

        jMenuItemCadUsuario.setText("Usuarios");
        jMenuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatorios");

        jMenuItemRelPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelPaciente.setText("Pacientes");
        jMenuItemRelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelPacienteActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelPaciente);

        jMenuItem3.setText("Médicos");
        jMenuRelatorios.add(jMenuItem3);

        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindos");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenu1.setText("Agenda");

        jMenuItem1.setText("Agenda de Hoje");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agenda Médico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(845, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuarioActionPerformed
         try {
            conecta.executaSql("SELECT * FROM usuarios WHERE uso_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
          
            if (conecta.rs.getString("uso_tipo").equals("administrador")) {
                    if (telaUsu == null) {
                    telaUsu = new FormUsuario();
                    telaUsu.setVisible(true);
                }else{
                    telaUsu.setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Você não tem permissão de Administrador para esse recurso.\n Somente Administradores podem cadastrar novos médicos.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Você não tem permissão de Administrador para esse recurso.\n Somente Administradores podem cadastrar novos médicos..");
        }
        
        
    }//GEN-LAST:event_jMenuItemCadUsuarioActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        jInternalFrameInternal.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        jInternalFrameInternal.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedicoActionPerformed
        
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE uso_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
          
            if (conecta.rs.getString("uso_tipo").equals("administrador")) {
                if (tela == null) {
                    tela = new FormMedico();
                    tela.setVisible(true);
                }else{
                    tela.setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Você não tem permissão de Administrador para esse recurso.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Você não tem permissão de Administrador para esse recurso."+ex);
        }
        
    }//GEN-LAST:event_jMenuItemCadMedicoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE uso_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
          
            if (conecta.rs.getString("uso_tipo").equals("administrador")) {
                if (tela == null) {
                    tela = new FormMedico();
                    tela.setVisible(true);
                }else{
                    tela.setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Você não tem permissão de Administrador para esse recurso.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Você não tem permissão de Administrador para esse recurso."+ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacienteActionPerformed
        if (telaPas == null) {
                    telaPas = new FormPaciente();
                    telaPas.setVisible(true);
                }else{
                    telaPas.setVisible(true);
                }
    }//GEN-LAST:event_jMenuItemCadPacienteActionPerformed

    private void jButtonCadPAcienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPAcienteActionPerformed
        if (telaPas == null) {
                    telaPas = new FormPaciente();
                    telaPas.setVisible(true);
                }else{
                    telaPas.setVisible(true);
                }
    }//GEN-LAST:event_jButtonCadPAcienteActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        if (telaAge == null) {
                    telaAge = new FormAgenda();
                    telaAge.setVisible(true);
                }else{
                    telaAge.setVisible(true);
                    telaAge.setResizable(false);
                }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (telaAgen == null) {
                    telaAgen = new FormAgendados();
                    telaAgen.setVisible(true);
                }else{
                    telaAgen.setVisible(true);
                    telaAgen.setResizable(false);
                }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (telaAgenM == null) {
                    telaAgenM = new FormAgendaMedico();
                    telaAgenM.setVisible(true);
                }else{
                    telaAgenM.setVisible(true);
                    telaAgenM.setResizable(false);
                }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemRelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelPacienteActionPerformed
        //Esse metodo vai chamar nosso relatório de pacientes
            
        try {
            conecta.executaSql("SELECT * FROM pacientes order by pac_nome");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("C:\\Users\\Valdir\\Desktop\\Relatorios\\Relatório de Pacientes.jasper", new HashMap(),relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemRelPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadEnfermeiras;
    private javax.swing.JButton jButtonCadPAciente;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JInternalFrame jInternalFrameInternal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCadEnfermeira;
    private javax.swing.JMenuItem jMenuItemCadMedico;
    private javax.swing.JMenuItem jMenuItemCadPaciente;
    private javax.swing.JMenuItem jMenuItemCadUsuario;
    private javax.swing.JMenuItem jMenuItemRelPaciente;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("LogoCentro.png")));
    }
    
}
